# Generated by Django 3.2.8 on 2021-11-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcementId', models.AutoField(primary_key=True, serialize=False)),
                ('dateAnn', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='Uploaded Files/')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('shortName', models.CharField(max_length=50)),
                ('longName', models.CharField(max_length=50)),
                ('society', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('companyEmail', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname1', models.CharField(max_length=50)),
                ('surname2', models.CharField(max_length=50)),
                ('personEmail', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('company_prn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semesterId', models.AutoField(primary_key=True, serialize=False)),
                ('semesterName', models.CharField(max_length=7)),
                ('semesterPassword', models.CharField(default='NNa1IeChAFGpdiF', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PseeAnn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_pseeann', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.announcement')),
                ('prn_pseeann', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='role_prn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
        migrations.AddField(
            model_name='person',
            name='semester_prn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.semester'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='person_ann',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
    ]
