# Generated by Django 3.2.8 on 2021-12-01 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcementId', models.AutoField(primary_key=True, serialize=False)),
                ('dateAnn', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('file', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'announcement',
                'verbose_name_plural': 'announcement',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('shortName', models.CharField(max_length=50, unique=True)),
                ('longName', models.CharField(max_length=50)),
                ('society', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('companyEmail', models.EmailField(max_length=50)),
                ('statusCompany', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('homeworkId', models.AutoField(primary_key=True, serialize=False)),
                ('tittleHw', models.CharField(max_length=50)),
                ('descriptionHw', models.CharField(max_length=300)),
                ('dateDeliveryHw', models.DateTimeField()),
                ('datePublicationHw', models.DateTimeField(auto_now_add=True)),
                ('statusHw', models.BooleanField()),
                ('fileHw', models.CharField(max_length=2000)),
                ('gradeHw', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'homework',
                'verbose_name_plural': 'homeworks',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offerId', models.AutoField(primary_key=True, serialize=False)),
                ('dateOffer', models.DateTimeField(auto_now_add=True)),
                ('descriptionOffer', models.CharField(max_length=500)),
                ('fileOffer', models.CharField(max_length=2000)),
                ('minOffer', models.IntegerField()),
                ('maxOffer', models.IntegerField()),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semesterId', models.AutoField(primary_key=True, serialize=False)),
                ('semesterName', models.CharField(max_length=7)),
                ('semesterPassword', models.CharField(default='C0Q3kyWlAEemTpB', max_length=20)),
            ],
            options={
                'verbose_name': 'semester',
                'verbose_name_plural': 'semesters',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname1', models.CharField(max_length=50)),
                ('surname2', models.CharField(max_length=50)),
                ('personEmail', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('announcements', models.ManyToManyField(blank=True, to='api.Announcement')),
                ('company_prn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('offers', models.ManyToManyField(blank=True, to='api.Offer')),
                ('role_prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
                ('semester_prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.semester')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='homework',
            field=models.ManyToManyField(blank=True, to='api.Homework'),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendarId', models.AutoField(primary_key=True, serialize=False)),
                ('descriptionCalendar', models.CharField(max_length=300)),
                ('observationCalendar', models.CharField(max_length=500)),
                ('dateCalendar', models.DateField(auto_now_add=True)),
                ('company_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'verbose_name': 'calendar',
                'verbose_name_plural': 'calendars',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceId', models.AutoField(primary_key=True, serialize=False)),
                ('dateAttendance', models.DateField()),
                ('noteAttendance', models.CharField(max_length=500)),
                ('statusAttendance', models.IntegerField()),
                ('gradeAttendance', models.IntegerField()),
                ('gradePOV', models.IntegerField()),
                ('person_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendances',
            },
        ),
    ]
