# Generated by Django 3.2.8 on 2021-12-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semesterPassword',
            field=models.CharField(default='qCrv8n1s9xhVMF2', max_length=20),
        ),
    ]
