# Generated by Django 3.2.8 on 2021-11-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_semester_semesterpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semesterPassword',
            field=models.CharField(default='8x32ysqLHdfgfXI', max_length=20),
        ),
    ]
