# Generated by Django 3.2.8 on 2021-11-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_semester_semesterpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semesterPassword',
            field=models.CharField(default='KB3t1aFx0PwpQ4y', max_length=20),
        ),
    ]
