# Generated by Django 3.2.8 on 2021-11-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_semester_semesterpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='file',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='offer',
            name='fileOffer',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semesterPassword',
            field=models.CharField(default='y2gK28sX7upmicH', max_length=20),
        ),
    ]
