# Generated by Django 3.2.8 on 2021-11-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_semester_semesterpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semesterPassword',
            field=models.CharField(default='JQris6C0428xWOy', max_length=20),
        ),
    ]
