# Generated by Django 3.2.8 on 2021-11-30 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_semester_semesterpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('homeworkId', models.AutoField(primary_key=True, serialize=False)),
                ('tittleHw', models.CharField(max_length=50)),
                ('descriptionHw', models.CharField(max_length=300)),
                ('dateDeliveryHw', models.DateTimeField()),
                ('datePublicationHw', models.DateTimeField(auto_now_add=True)),
                ('statusHw', models.BooleanField()),
                ('fileHw', models.CharField(max_length=2000)),
                ('gradeHw', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'homework',
                'verbose_name_plural': 'homeworks',
            },
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'announcement', 'verbose_name_plural': 'announcement'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'offer', 'verbose_name_plural': 'offers'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'semester', 'verbose_name_plural': 'semesters'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='companyId',
        ),
        migrations.AddField(
            model_name='company',
            name='statusCompany',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='shortName',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semesterPassword',
            field=models.CharField(default='rjtVN2c9xElJM3V', max_length=20),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendarId', models.AutoField(primary_key=True, serialize=False)),
                ('descriptionCalendar', models.CharField(max_length=300)),
                ('observationCalendar', models.CharField(max_length=500)),
                ('dateCalendar', models.DateField(auto_now_add=True)),
                ('company_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'verbose_name': 'calendar',
                'verbose_name_plural': 'calendars',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceId', models.AutoField(primary_key=True, serialize=False)),
                ('dateAttendance', models.DateField()),
                ('noteAttendance', models.CharField(max_length=500)),
                ('statusAttendance', models.IntegerField()),
                ('gradeAttendance', models.IntegerField()),
                ('gradePOV', models.IntegerField()),
                ('person_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendances',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='homework',
            field=models.ManyToManyField(blank=True, to='api.Homework'),
        ),
    ]
