# Generated by Django 3.2.8 on 2021-11-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211129_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semesterPassword',
            field=models.CharField(default='6CM3z9lxmsSDVfL', max_length=20),
        ),
    ]
