# Generated by Django 3.2.8 on 2021-11-18 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('shortName', models.CharField(max_length=50)),
                ('longName', models.CharField(max_length=50)),
                ('society', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('companyEmail', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname1', models.CharField(max_length=50)),
                ('surname2', models.CharField(max_length=50)),
                ('personEmail', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('company_prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.company')),
                ('role_prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.role')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
            },
        ),
    ]
