# Generated by Django 3.1.2 on 2021-11-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semesterID', models.AutoField(primary_key=True, serialize=False)),
                ('semestername', models.CharField(max_length=7)),
            ],
        ),
    ]
