# Generated by Django 3.1.2 on 2021-11-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='codigo',
            field=models.CharField(default='Buoxoq59Wn9OkrI', max_length=20),
        ),
    ]
