# Generated by Django 3.1.2 on 2021-11-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_semester_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semestername',
            new_name='semesterName',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='codigo',
        ),
        migrations.AddField(
            model_name='semester',
            name='semesterPassword',
            field=models.CharField(default='tiQwesR7sJB3puS', max_length=20),
        ),
    ]
