# Generated by Django 3.1.2 on 2021-11-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20211122_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semesterID',
            new_name='semesterId',
        ),
        migrations.AlterField(
            model_name='semester',
            name='semesterPassword',
            field=models.CharField(default='2TJFjJEr9GyQFdw', max_length=20),
        ),
    ]
