# Generated by Django 3.1.2 on 2021-11-23 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20211122_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='semester_prn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semesterPassword',
            field=models.CharField(default='vrOFP6B5ktn0LrF', max_length=20),
        ),
    ]
