# Generated by Django 3.1.2 on 2021-11-23 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20211122_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='semester_prn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semesterPassword',
            field=models.CharField(default='IiJqQKl9O8KEVAS', max_length=20),
        ),
    ]
