# Generated by Django 3.1.2 on 2021-11-23 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20211122_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='company_prn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.company'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semesterPassword',
            field=models.CharField(default='NbWBUepplg2P52E', max_length=20),
        ),
    ]
