# Generated by Django 3.1.2 on 2021-11-23 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20211122_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcementId', models.AutoField(primary_key=True, serialize=False)),
                ('dateAnn', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='Uploaded Files/')),
                ('person_ann', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.person')),
            ],
        ),
        migrations.AlterField(
            model_name='semester',
            name='semesterPassword',
            field=models.CharField(default='QotNLOrKQCkVwj4', max_length=20),
        ),
        migrations.CreateModel(
            name='PseeAnn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_pseeann', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.announcement')),
                ('prn_pseeann', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.person')),
            ],
        ),
    ]
