# Generated by Django 3.2.8 on 2021-11-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20211122_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semesterPassword',
            field=models.CharField(default='svgmL379DUTD1ks', max_length=20),
        ),
    ]
