# Generated by Django 3.1.2 on 2021-10-06 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('correoELectronicoEmpresa', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name': 'grupoEmpresa',
                'verbose_name_plural': 'gruposEmpresas',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDeRol', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='Rol_usr',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupo_usr',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.grupoempresa'),
        ),
    ]
