# Generated by Django 3.1.2 on 2021-10-06 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20211006_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Rol_usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grupo_usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.grupoempresa'),
        ),
    ]
