# Generated by Django 3.2.8 on 2021-10-08 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20211007_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupoempresa',
            old_name='id',
            new_name='grupoId',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='id',
            new_name='rolId',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id',
            new_name='usuarioId',
        ),
    ]
