# Generated by Django 3.2.8 on 2021-10-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20211008_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupoempresa',
            old_name='correoELectronicoEmpresa',
            new_name='correoEmpresa',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Rol_usr',
            new_name='rol_usr',
        ),
    ]
